Information:
  Title: DevCreates
  Icon: icon.png
  Description: DevCreates is a Discord community and guild who has the 'Dev' tag! We have a blog made with Writea to help others learn more about developing.
  Link: discord.gg/devcreates
  Theme: Default

Connections:
  GitHub: TheDevCreates
  YouTube: devcreates-community